<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ZipStream\\' => array($vendorDir . '/maennchen/zipstream-php/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Picqer\\Barcode\\' => array($vendorDir . '/picqer/php-barcode-generator/src'),
    'Phroute\\Phroute\\' => array($vendorDir . '/phroute/phroute/src/Phroute'),
    'PhpOffice\\PhpSpreadsheet\\' => array($vendorDir . '/phpoffice/phpspreadsheet/src/PhpSpreadsheet'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'MyCLabs\\Enum\\' => array($vendorDir . '/myclabs/php-enum/src'),
    'Matrix\\' => array($vendorDir . '/markbaker/matrix/classes/src'),
    'Hashids\\' => array($vendorDir . '/hashids/hashids/src'),
    'Delight\\Http\\' => array($vendorDir . '/delight-im/http/src'),
    'Delight\\Db\\' => array($vendorDir . '/delight-im/db/src'),
    'Delight\\Cookie\\' => array($vendorDir . '/delight-im/cookie/src'),
    'Delight\\Base64\\' => array($vendorDir . '/delight-im/base64/src'),
    'Delight\\Auth\\' => array($vendorDir . '/delight-im/auth/src'),
    'Complex\\' => array($vendorDir . '/markbaker/complex/classes/src'),
);
